### ISSUE TITLE
MVP sentiment analysis

### ISSUE THREAD

**Issue by BrianThomasRoss** [Salty-Hackers/data-engineering#2]
- [x] Use VADER to perform sentiment analysis on minimal data set
- [x] Productionize model as a class object
- [x] Create processed data set with top 1000 "saltiest" users

**Comment by ryankoul** [comment]
Datasets: We used Vader to estimate sentiment scores and used pandas to feature engineer sentiment (positive, negative, neutral) and sentiment rank. App: The threshold of saltiest users is set to 100 as a POST request, but it can be increased to  1,000. We also added a min_comments threshold if a user wants only the saltiest hackers with, say, at least 10 comments.
